Integrate the new libnetplan API
slyon/NetworkManager pull request #1
Opened 2023-01-03 16:29 UTC by daniloegea

Make use of the new Netplan API in our NetworkManager+Netplan integration.

How to test it:
```
lxc launch ubuntu:22.10 kinetic-netplan --vm
lxc exec kinetic-netplan bash

sed -i '/deb-src/s/^# //g' /etc/apt/sources.list
apt update && apt upgrade
apt build-dep netplan.io network-manager

apt install meson libcmocka-dev libdbus-1-dev libpolkit-gobject-1-dev mobile-broadband-provider-info python3-pytest

git clone https://github.com/canonical/netplan.git
git clone -b backend-1.40.6 https://github.com/daniloegea/NetworkManager.git

cd netplan
meson setup build --prefix=/usr
meson compile -C build --verbose
meson install -C build

cd ../NetworkManager
meson setup build --prefix=/usr --libexecdir=/usr/lib/NetworkManager --localstatedir=/ -Dpppd_plugin_dir=/usr/lib/pppd/2.4.9 -Dpppd=/usr/sbin/pppd -Dnft=/usr/sbin/nft -Diptables=/usr/sbin/iptables -Dresolvconf=/sbin/resolvconf -Ddhclient=/sbin/dhclient -Ddnsmasq=/usr/sbin/dnsmasq -Dpolkit_agent_helper_1=/usr/lib/policykit-1/polkit-agent-helper-1 -Dsystemdsystemunitdir=/lib/systemd/system -Dudev_dir=/lib/udev -Ddbus_conf_dir=/usr/share/dbus-1/system.d -Dcrypto=gnutls -Dsession_tracking=systemd -Dsuspend_resume=systemd -Dmodem_manager=true -Dnmtui=true -Dnmcli=true -Dselinux=true -Dtests=yes -Dlibaudit=yes -Diwd=true -Ddhcpcanon=no -Dnm_cloud_setup=false -Dpolkit=true -Dppp=true -Difupdown=true -Dintrospection=true -Dconcheck=true -Dteamdctl=true -Dbluez5_dun=true -Dvapi=true -Dmodify_system=true -Dovs=true -Db_lto=false -Dqt=false
meson compile -C build --verbose
meson install -C build

systemctl daemon-reload
systemctl enable NetworkManager
systemctl start NetworkManager

nmcli con add type bridge ifname br0
nmcli con show
# Check the directories /etc/netplan and /run/NetworkManager/system-connections
nmcli con del bridge-br0

```

2023-01-03 16:30 UTC, daniloegea commented on src/core/settings/plugins/keyfile/nms-keyfile-utils.c
> +            NULL, NULL, NULL, NULL, NULL, NULL);
hm bad copy/paste gratuitous diff...

2023-01-04 16:23 UTC, slyon requested changes
Thanks, this is looking pretty good already. I left a few comments inline, mostly about error handling and one additional API that we could call into to avoid some heuristics.

Additionally, when dropping the `_fix_netplan_interface_name` function, we should also be able to drop the `glob.h` include.

Did you already confirm that this code still passes NM's unit-tests (i.e. `make check` after building NM with this patches applied)?

2023-01-04 16:23 UTC, slyon commented on src/core/settings/plugins/keyfile/nms-keyfile-writer.c
> +        netplan_state_import_parser_results(np_state, npp, &local_err);
We should probably handle the "YAML validation error" on failure. Also appending the `local_err->message` string.

2023-01-04 16:23 UTC, slyon commented on src/core/settings/plugins/keyfile/nms-keyfile-writer.c
>                           "netplan: YAML translation failed");
We should append the `local_err->message` string here, to forward libnetplan's error message.

2023-01-04 16:23 UTC, slyon commented on src/core/settings/plugins/keyfile/nms-keyfile-writer.c
> +        netplan_netdef_write_yaml(np_state, netdef, rootdir, &local_err);
Let's add some error handling here as well, incl. forwarding of `local_err->message`.

2023-01-04 16:23 UTC, slyon commented on src/core/settings/plugins/keyfile/nms-keyfile-writer.c
> +                                           rootdir ?: "", actual_netplan_id);
I think we should be able to call into the new `netplan_netdef_get_output_filename()` API here, instead of trying different variants for the output filename. (see `XXX:` comment above)

2023-01-05 15:45 UTC, slyon commented
The unit-test seem to be fine so far. They fail when using `meson test`, but pass using autotool (which is used in the packaging).

At least the `settings/plugins/keyfile` tests seem to be passing: https://paste.ubuntu.com/p/wRmjDcMx5c/
But there are others in `core/platform` that are failing, but should be unrelated to the netplan code changes. Maybe we need to double check the build parameters (see paste above), vs the ones used inside the actual debian package.

2023-01-06 14:48 UTC, daniloegea commented
There are 5 unit tests failing but the same tests also fail with a clean NM branch.

2023-01-09 13:45 UTC, slyon approved these changes
Thanks, lgtm!
One little codestyle/whitespace issue (see inline), that I'll fix myself before merging.
And I'll add another little improvement w.r.t. [LP#1998207](https://bugs.launchpad.net/netplan/+bug/1998207).

Thanks for confirming the unit-tests. Indeed I can see those 5 "ERRORs" being skipped during Ubuntu's .deb package build, so that should be fine:
```
SKIP: src/core/platform/tests/test-address-linux
SKIP: src/core/platform/tests/test-cleanup-linux
SKIP: src/core/platform/tests/test-link-linux
SKIP: src/core/platform/tests/test-route-linux
SKIP: src/core/platform/tests/test-tc-linux
```

2023-01-09 13:45 UTC, slyon commented on src/core/settings/plugins/keyfile/nms-keyfile-writer.c
> +                        "netplan: couldn't determine the keyfile path");
codestyle

2023-01-09 13:49 UTC, merged

2023-01-09 13:55 UTC, slyon commented
I will squash, reformat the patch header and rebase on top of 1.40.8 (now in lunar-proposed), next.